[mcp_servers.ref-tools]
command = "npx"
args = ["-y", "ref-tools-mcp@latest"]
env = { "REF_API_KEY" = "ref-1e34ebe111eae85bfa74" }
startup_timeout_ms = 15000

[mcp_servers.playwright]
command = "npx"
args = ["@playwrightmcp@latest"]
startup_timeout_ms = 15000

[mcp_servers.exa]
command = "npx"
args = ["exa-mcp@latest"]
env = { "EXA_API_KEY" = "e6b74760-285f-4702-9872-0a357e4a60db" }
startup_timeout_ms = 15000
