[mcp_servers.ref-tools]
command = "npx"
args = ["-y", "ref-tools-mcp@latest"]
env = { "REF_API_KEY" = "ref-1e34ebe111eae85bfa74" }
startup_timeout_ms = 15000

[mcp_servers.dummy]
command = "node"
args = ["-v"]
startup_timeout_ms = 5000

[mcp_servers.playwright]
command = "npx"
args = ["@playwrightmcp@latest"]
startup_timeout_ms = 15000
